//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by obranditem.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_OBRANDITEM_FORM             101
#define IDD_ITEMVIEW                    102
#define IDD_GENERATEVIEW                103
#define IDD_ERRORVIEW                   104
#define IDR_MAINFRAME                   128
#define IDR_OBRANDTYPE                  129
#define IDD_LVLI_DLG                    130
#define IDD_ENCH_DLG                    131
#define IDD_WEAP_DLG                    132
#define IDD_ARMO_DLG                    133
#define IDD_CLOT_DLG                    134
#define IDD_MISC_DLG                    135
#define IDD_SCPT_DLG                    136
#define IDD_BOOK_DLG                    137
#define IDD_LIGH_DLG                    138
#define IDD_SGST_DLG                    139
#define IDD_OPTIONS_DLG                 140
#define IDR_LIST_MENU                   141
#define IDC_RECORDLIST                  1000
#define IDC_GENERATE_BUTTON             1002
#define IDC_TABCTRL                     1003
#define IDC_OPTIONS_BUTTON              1003
#define IDC_TREECTRL                    1004
#define IDC_GENERATEMORE_BUTTON         1004
#define IDC_BASEITEMS_TEXT              1005
#define IDC_BROWSE_BASEITEMS            1006
#define IDC_EFFECTS_TEXT                1007
#define IDC_BROWSE_EFFECTS              1008
#define IDC_UNIQUES_TEXT                1009
#define IDC_BROWSE_UNIQUES              1010
#define IDC_BASEITEM_COUNT              1011
#define IDC_SUFFIX_COUNT                1012
#define IDC_PREFIX_COUNT                1013
#define IDC_UNIQUES_COUNT               1014
#define IDC_NEWITEMS_COUNT              1015
#define IDC_PREFIX_CHANCE               1016
#define IDC_SUFFIX_CHANCE               1017
#define IDC_UNIQUE_CHANCE               1018
#define IDC_PROGRESSBAR                 1019
#define IDC_IDPREFIX_TEXT               1020
#define IDC_IDTYPE_LIST                 1021
#define IDC_NUMITEMS_TEXT               1022
#define IDC_MINLEVEL_TEXT               1023
#define IDC_MAXLEVEL_TEXT               1024
#define IDC_ARMOR_CHECK                 1025
#define IDC_SCROLL_CHECK                1026
#define IDC_ERRORTEXT                   1026
#define IDC_WEAPON_CHECK                1027
#define IDC_CLOTHING_CHECK              1028
#define IDC_MAXNAMELENGTH_TEXT          1029
#define IDC_EXTID_TEXT                  1029
#define IDC_CREATELIST_CHECK            1030
#define IDC_EDITORID                    1030
#define IDC_NAMEDELIMITER_TEXT          1030
#define IDC_MISC_CHECK                  1031
#define IDC_CALCULATEALL                1031
#define IDC_FORMID                      1031
#define IDC_OFSTRING_TEXT               1031
#define IDC_STAFF_CHECK                 1032
#define IDC_CALCULATEEACH               1032
#define IDC_ITEMNAME                    1032
#define IDC_MATERIALCHANCE_TEXT         1032
#define IDC_ESPFILE_TEXT                1033
#define IDC_CHANCENONE                  1033
#define IDC_BROWSE_ESPFILE              1034
#define IDC_ITEM_LIST                   1034
#define IDC_LEVELLISTS_TEXT             1035
#define IDC_TYPE                        1035
#define IDC_FORMID2                     1035
#define IDC_BROWSE_LEVELLISTS           1036
#define IDC_AUTOCALC                    1036
#define IDC_WEIGHT                      1036
#define IDC_TEXT                        1036
#define IDC_CHARGE                      1037
#define IDC_VALUE                       1037
#define IDC_WEIGHT2                     1037
#define IDC_RANDOMBELL_CHECK            1037
#define IDC_COST                        1038
#define IDC_HEALTH                      1038
#define IDC_VALUE2                      1038
#define IDC_RANDOMBELL_TEXT             1038
#define IDC_EFFECT_LIST                 1039
#define IDC_ARMORCOUNT_TEXT             1039
#define IDC_TEACHES                     1039
#define IDC_TIME                        1039
#define IDC_NAME                        1040
#define IDC_CLOTHINGCOUNT_TEXT          1040
#define IDC_DAMAGE                      1041
#define IDC_MISCCOUNT_TEXT              1041
#define IDC_BIPEDPARTS                  1041
#define IDC_FALLOFF                     1041
#define IDC_SPEED                       1042
#define IDC_SCROLLCOUNT_TEXT            1042
#define IDC_FOV                         1042
#define IDC_REACH                       1043
#define IDC_STAFFCOUNT_TEXT             1043
#define IDC_RADIUS                      1043
#define IDC_ENCHANTMENT                 1044
#define IDC_WEAPONCOUNT_TEXT            1044
#define IDC_COLOR                       1044
#define IDC_LEVELLIST_COUNT             1045
#define IDC_ENCHANTCHARGE               1045
#define IDC_FADE                        1045
#define IDC_MERGEDESPFILE_TEXT          1046
#define IDC_IGNORERESIST                1046
#define IDC_BROWSE_MERGEDESPFILE        1047
#define IDC_SCRIPT                      1047
#define IDC_EDIT_ENCHANTMENT            1048
#define IDC_REMOVENORMAL_CHECK          1048
#define IDC_EDIT_SCRIPT                 1049
#define IDC_ITEMS_CHECK                 1049
#define IDC_REMOVEDUPLICATES_CHECK      1049
#define IDC_MODEL                       1050
#define IDC_LIGHT_CHECK                 1050
#define IDC_CHECKUPLICATES_CHECK        1050
#define IDC_ICONTEXT                    1051
#define IDC_LIGHTCOUNT_TEXT             1051
#define IDC_HIDEPREFIX2_CHECK           1051
#define IDC_HIDERINGS                   1052
#define IDC_USERDATA                    1052
#define IDC_SIGIL_CHECK                 1052
#define IDC_CREATELISTPARENTS_CHECK     1052
#define IDC_HIDEAMULET                  1053
#define IDC_SIGILLCOUNT_TEXT            1053
#define IDC_SOUNDTEXT                   1053
#define IDC_ARMOR                       1054
#define IDC_USERDATA2                   1054
#define IDC_MALEBIPED                   1055
#define IDC_MALEWORLD                   1056
#define IDC_MALEICON                    1057
#define IDC_FEMALEWORLD                 1058
#define IDC_FEMALEICON                  1059
#define IDC_FEMALEBIPED                 1060
#define IDC_PLAYABLE                    1061
#define IDC_USERDATA3                   1062
#define IDC_SCROLL                      1062
#define IDC_FLICKER                     1063
#define IDC_CARRIED                     1064
#define IDC_DEFAULTOFF                  1065
#define IDC_USES                        1065
#define IDC_NEGATIVE                    1066
#define IDC_DYNAMIC                     1067
#define IDC_SPOTLIGHT                   1068
#define IDC_SPOTSHADOW                  1069
#define ID_HELP_SIWIKIARTICLEATUESP     32771
#define ID_HELP_SIWIKIARTICLE           32772
#define ID_FILE_SAVEESP                 32773
#define ID_VIEW_OPTIONS                 32774
#define ID_LISTMENU_GENERATIONDETAILS   32775
#define ID_FILE_RUNBATCH                32776
#define ID_VIEW_TEST                    32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1066
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
